name: Build and publish release
on:
  push:
    tags:
      - 'v?[0-9].[0-9].[0-9]'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - uses: clairelizbet/action-build@v1
      - uses: clairelizbet/action-test@v1

      - uses: actions/download-artifact@v3
        with:
          name: build-${{ github.sha }}
